services:
  backend:
    build:  
      context: ./  # The context (directory) to create the backend must match while creating the image
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:test123@db:5432/mydb # Fixed typo in `postgresql`
    depends_on:
      - db
    volumes:  # Added so backend changes reflect and create a new image on docker
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:15  # The image we are pulling
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres  # Fixed typo in `POSTGES_USER`
      POSTGRES_PASSWORD: test123  # Fixed typo in `POSTGES_PASSWORD`
      POSTGRES_DB: mydb  # Fixed typo in `POSTGES_DB`
    ports:
      - "5432:5432"  # LocalPort:ContainerPort
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data

volumes:
  postgres_data :  # Named volume for database persistence


#to run docker compose -> docker compose up -- build  this will create docker image with running
#docker have 4 type of volumes 1) bind 2)named 3)anonyms 4) tmps mount